server:
  port: 8082

spring:
  application:
    name: ratelimiter

resilience4j:
  ratelimiter:
    instances:
      rateLimitingAPI:
        limitForPeriod: 5
        limitRefreshPeriod: 15s
        timeoutDuration: 5s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
#    metrics:
#      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    ratelimiters:
      enabled: true