server:
  port: 8083

spring:
  application:
    name: bulkhead

resilience4j:
  bulkhead:
    instances:
      FIRST_BULKHEAD:
        max-concurrent-calls: 20
      SECOND_BULKHEAD:
        max-concurrent-calls: 20
    metrics:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always