server:
  port: 8082

spring:
  application:
    name: bulkhead

resilience4j:
  bulkhead:
    instances:
      FIRST_BULKHEAD:
        max-concurrent-calls: 20
      SECOND_BULKHEAD:
        max-concurrent-calls: 20